name: Check the code with linters

on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Run markdownlint in docker container
        run: |
          docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest "content/*.md content/blog/*.md"
